title: ghpages-test
description: A minimal GitHub Pages / Jekyll site
baseurl: "" # change if site is hosted in a subpath
url: ""     # set to https://your-site.example when deploying
markdown: kramdown
# theme: minima
